language: java
jdk:
- oraclejdk8
sudo: required
dist: trusty
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
script:
-  |
    echo "Running Spring Cloud Contract Verifier"
    ./mvnw clean install
    cd spring-cloud-contract-verifier-gradle-plugin
    ./gradlew clean build install

    echo "Checking if samples are not broken"
    cd ..
    ./scripts/runTests.sh
env:
  global:
  - TERM=dumb