language: java
jdk:
- oraclejdk8
script:
-  |
    echo "Running Spring Cloud Contract Verifier tests"
    cd spring-cloud-contract-verifier/spring-cloud-contract-verifier
    ./gradlew clean build install
- |
    echo "Running Spring Cloud Contract Verifier Maven Plugin tests"
    cd spring-cloud-contract-verifier/spring-cloud-contract-verifier-maven-plugin
    ./mvnw clean install jacoco:report coveralls:report -pl spring-cloud-contract-verifier-maven-plugin
-  |
    echo "Checking if samples are not broken"
    cd spring-cloud-contract-verifier/spring-cloud-contract-verifier
    ./scripts/runTests.sh
env:
  global:
  - TERM=dumb