language: java
sudo: required
dist: trusty

before_install:
 - "export JAVA_OPTS='-Xmx1024m -XX:MaxPermSize=256m'"

jdk:
 - oraclejdk7
 - oraclejdk8

install: ./gradlew assemble
script: ./gradlew clean check funcTest --stacktrace --continue
